name: Sync with Hugging Face Hub

on:
  workflow_run:
    workflows: ["Daily Stock Model Retrain"]
    types:
      - completed

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git lfs install
          git remote add hf https://HF_USERNAME:${HF_TOKEN}@huggingface.co/spaces/HF_USERNAME/SPACE_NAME
          git push hf HEAD:main --force
