name: Sync with Hugging Face Hub

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_run:
    workflows: ["Daily Stock Model Retrain"]
    types:
      - completed

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository (with LFS)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Set up Git LFS and fetch objects from origin
        run: |
          git lfs install
          # Ensure we have all LFS objects for the current branch from GitHub
          git lfs fetch --all origin
          git lfs checkout

      - name: Push to Hugging Face Hub (LFS first, then refs)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git lfs install
          git config lfs.allowincompletepush true
          git remote add hf https://hrk6378:${HF_TOKEN}@huggingface.co/spaces/hrk6378/smol-pp || true
          # Upload all LFS objects referenced by the branch to HF
          git lfs push --all hf main
          # Push Git refs
          git push hf HEAD:main --force
