name: Sync with Hugging Face Hub

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Daily Stock Model Retrain"]
    types:
      - completed

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true   # ✅ Pull full LFS files from GitHub repo


      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs pull     # ✅ Ensure actual binary files are downloaded

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git lfs install
          git config lfs.allowincompletepush true
          git remote add hf https://hrk6378:${HF_TOKEN}@huggingface.co/spaces/hrk6378/smol-pp
          # ✅ Explicitly push all LFS objects to HF storage
          git lfs push hf main --all
          git push hf HEAD:main --force
