name: Daily Stock Model Retrain

on:
  workflow_dispatch:          # Allow manual trigger too
  schedule:
    # Run at 21:30 UTC (9:30 PM UTC) on weekdays (Mon-Fri)
    # US Market closes at 4:00 PM EST (21:00 UTC) / 4:00 PM EDT (20:00 UTC)
    # This runs 1.5-2.5 hours after market close to ensure data availability
    # Converts to: 2:30 AM IST (UTC+5:30) or 5:30 PM EST / 4:30 PM EDT
    # - cron: '30 4 * * 1-6'
    
    # Test run at 1:22 AM IST (19:52 UTC)
    - cron: '0 10 * * *'
  

permissions:
  contents: write

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch latest intraday data
        run: python fetch_intraday.py

      - name: Train and update ML models
        run: python model_trainer.py

      - name: Commit and push changes to main branch
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git config --global user.email "bot@example.com"
            git config --global user.name "GitHub Actions Bot"
            git add data/*.csv models/*.h5 models/*.pkl models/*.json
            git commit -m "$(date +'%Y-%m-%d') - Daily data fetch and model update" || echo "No changes to commit"
            git push origin main
        
